// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZrPrKSFtlFBu7Ug_fonDcQW0Ak8V0D40',
    appId: '1:627505729716:web:368ef884b03044e7a307e1',
    messagingSenderId: '627505729716',
    projectId: 'wasta-8d4f4',
    authDomain: 'wasta-8d4f4.firebaseapp.com',
    storageBucket: 'wasta-8d4f4.appspot.com',
    measurementId: 'G-5P8RXP55XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTRPk7dQZB0U9ijcNg457RsTHdm9Gt0Cw',
    appId: '1:627505729716:android:b00928b329e03b0ea307e1',
    messagingSenderId: '627505729716',
    projectId: 'wasta-8d4f4',
    storageBucket: 'wasta-8d4f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXR53W-nVoF8HmYLu23SYl8389phExrdE',
    appId: '1:627505729716:ios:d5444a2944b4dc66a307e1',
    messagingSenderId: '627505729716',
    projectId: 'wasta-8d4f4',
    storageBucket: 'wasta-8d4f4.appspot.com',
    iosClientId: '627505729716-9nl23hj29hvlatfddbbdjsgq97qd1qe6.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXR53W-nVoF8HmYLu23SYl8389phExrdE',
    appId: '1:627505729716:ios:d5444a2944b4dc66a307e1',
    messagingSenderId: '627505729716',
    projectId: 'wasta-8d4f4',
    storageBucket: 'wasta-8d4f4.appspot.com',
    iosClientId: '627505729716-9nl23hj29hvlatfddbbdjsgq97qd1qe6.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasta',
  );
}
